account/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path("profile/<user_id>/", account_view , name="profile"),
    path("profile/<user_id>/edit/", edit , name="edit"),
    path("profile/<user_id>/friends/", list_friends , name="list-friends"),
    path("profile/<user_id>/frequest/", list_friend_requests , name="list-friend-requests"),
    path("profile/<id>/add/", send_friend_request , name="add-friend"),
    path("profile/<id>/accept/", accept_friend_request , name="accept-friend"),
    path("profile/<user_id>/remove/", remove_friend , name="remove-friend"),
    path('register/', register, name="register"),
    path('login/', LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='account/logout.html'), name='logout'),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
]

chat/urls.py
from django.urls import path
from .views import *

app_name = 'chat'

urlpatterns = [
    path('', home, name="home"),
    path('search', search, name="search"),
    path('rooms', list_public_chat_rooms, name="list_rooms"),
    path('room/<slug:slug>', join_room, name="join_room"),
]

djangochat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls', namespace='chat')),
    path('account/', include('account.urls', namespace='account'),
    )
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from account.models import Account

# Create your models here.

class Room(models.Model):
        name            = models.CharField("Name", max_length=50)
        slug            = models.SlugField("Slug", unique=True)
        owner           = models.ForeignKey("account.Account", verbose_name="Owner", related_name="owner", on_delete=models.CASCADE)
        # date_created    = models.DateTimeField("Date Created", auto_now=False, auto_now_add=False)

        def __str__(self):
                return self.name

class Message(models.Model):
        room            = models.ForeignKey(Room, verbose_name="Room", related_name='room', on_delete=models.CASCADE)
        user            = models.ForeignKey("account.Account", verbose_name="User", related_name="user", on_delete=models.CASCADE)
        message         = models.TextField()
        date_created    = models.DateTimeField("Date Created", auto_now_add=True)

        class Meta:
                ordering = ('date_created',)

chat/views.py
from django.shortcuts import render
from account.models import Account
from .models import Message, Room

# Create your views here.
def home(request):
        return render(request, 'chat/home.html')

def search(request):
        context = {}
        if request.method == 'GET':
                search_q = request.GET['friend']
                if len(search_q) > 0:
                        users = Account.objects.filter(username__contains=search_q)
                        # users = Account.objects.all()
                        context['users'] = users
        return render(request, 'chat/home.html', context)

def list_public_chat_rooms(request):
        context = {}

        all_rooms        = Room.objects.all()
        user_rooms       = Room.objects.filter(owner=request.user)

        context['all_rooms']     = all_rooms
        context['user_rooms']    = user_rooms

        return render(request, 'chat/rooms.html', context)

def join_room(request, slug):
        room = Room.objects.get(slug=slug)
        messages         = Message.objects.filter(room=room)[0:20]

        return render(request, 'chat/room.html', {
                'room'          :room,
                'messages'      : messages
        })

chat/templates/chat/home.html
{% extends "base.html" %}

{% block title %}  Chat With Django {% endblock title %}

{% block content %}
        <h2>Welcome, {{user.username}}</h2>
                <div class="list-users">
                        
                {% if users %}
                        {% for user in users %}
                        <div class="each-user">
                                <a href="{% url 'account:profile' user.id %}">
                                        <div class="username"><span>{{user.username}}</span></div>
                                        <div class="profile-img"><img src="{{user.profile_img.url}}" alt="Profile Image"></div>
                                </a>
                                <div class="friendship">
                                        {% if request.user.id == user.id %}
                                        <span class="check-friendship" style="display: inline;">You <i class="fa-solid fa-user" style="color: dodgerblue"></i></span>
                                        {% else %}
                                        <span class="check-friendship">Not Friends <i class="fa-solid fa-x" style="color: red; font-size: medium;"></i></i></span><br><br>
                                        <span class="message-user">Send a message <i class="fa-solid fa-message"></i></span>
                                        {% endif %}
                                </div>
                        </div>
                        {% endfor %}
                {% endif %}
                </div>
        </h2>
{% endblock content %}

chat/templates/chat/room.html
{% extends "base.html" %}

{% block title %}  {{room}} room {% endblock title %}

{% block content %}
        <style>
                .room {
                        width: 80%;
                        margin: 0 auto;
                        padding: 10px 5px;
                }
                .room-box {
                        padding: 10px 5px;
                        border-radius: 8px;
                        margin: 5px 10px;
                }
                .room-name {
                        font-size: xx-large;
                        text-transform: uppercase;
                        text-align: center;
                        font-weight: 600;
                        margin-bottom: 30px;
                }
                .messages {
                        overflow-y: auto;
                        height: 600px;
                        -ms-overflow-style: none;  /* Internet Explorer 10+ */
                        scrollbar-width: none;  /* Firefox */
                }
                .messages::-webkit-scrollbar { 
                        display: none;  /* Safari and Chrome */
                }
                .message-box {
                        width: 70%;
                        margin: 20px auto;
                        background-color: lightgray;
                        padding: 10px 5px;
                        border-radius: 8px;
                        box-shadow: 0px 5px 11px rgba(205, 205, 205, 0.8);
                        white-space: initial;
                }
                .message-box .username {
                        margin-left: 5px;
                        font-weight: 500;
                }
                .message-box .message {
                        margin-left: 5px;
                        margin-top: 5px;
                }
                .send-section {
                        width: 70%;
                        margin: 20px auto;
                        background-color: #ddd;
                        padding: 10px 5px;
                        border-radius: 8px;
                }
                .send-section form {
                        display: flex;
                        align-items: center;
                        justify-content: space-evenly;
                }
                .send-section form input {
                        padding: 10px 5px;
                        color: #111;
                        font-size: medium;
                        border: none;
                        outline: none;
                        background: transparent;
                        width: 70%;
                }
                .send-section form button {
                        background-color: purple;
                        outline: none;
                        border: none;
                        padding: 5px 10px;
                        font-size: medium;
                        border-radius: 5px;
                        cursor: pointer;
                }
        </style>

        <div class="room">
                <div class="room-box">
                        <div class="room-name">{{room.name}}</div>
                        <div class="messages">
                                {% for msg in messages %}
                                <div class="message-box">
                                        <span class="username">{{msg.user.username}}</span>
                                        <div class="message">
                                                <p class="content" style="display: inline;">{{msg.message}}</p>
                                                <div style="width: 80px; float: right; margin: 0 auto;"><small>{{msg.date_created |time:"H:i"}}</small></div>
                                        </div>
                                </div>
                                {% endfor %}
                        </div>
                        <div class="send-section">
                                {% csrf_token %}
                                <form method="post" action="">
                                        <input type="text" name="message" placeholder="Type something ..." id="message-input">
                                        <button type="submit" id="send-message-btn">Send</button>
                                </form>
                                
                        </div>
                </div>
        </div>
        
{% endblock content %}

{% block script %}
        {{room.slug | json_script:'json_roomslug'}}
        {{request.user.username | json_script:'json_username'}}
        <script>
                const roomName = JSON.parse(
                        document.getElementById('json_roomslug').textContent
                );
                const userName = JSON.parse(
                        document.getElementById('json_username').textContent
                );
                const chatSocket = new WebSocket(
                        'ws://' + window.location.host + '/ws/' + roomName + '/'
                );
                
                chatSocket.addEventListener('message', function (event) {
                        console.log('Message from server ', event.data);

                        const data      = JSON.parse(event.data)

                        if (data.message) {
                                let messagebox  = '<div class="message-box">';
                                messagebox+= '<span class="username">' + data.username + '</span>';
                                messagebox+= '<p class="message">' + data.message + '</p></div>';

                                let chatbox     = document.querySelector('.messages').innerHTML += messagebox;
                                scrl();
                        }
                        else {
                                alert('No Message (empty!)')
                        }
                    });
                chatSocket.addEventListener('close', function (event) {
                        console.log('closed ', event.data);
                    });

                // 

                document.getElementById('send-message-btn').onclick = function(event) {
                        event.preventDefault;
                        let messageInput        = document.getElementById('message-input');
                        let message             = messageInput.value;

                        chatSocket.send(JSON.stringify({
                                'message'       : message,
                                'username'      : userName,
                                'room'          : roomName
                        }));

                        messageInput.value = "";
                        
                        return false;
                }

                function scrl() {
                        const msgbox            = document.querySelector('.messages');
                        msgbox.scrollTop        = msgbox.scrollHeight;
                }

                scrl();
                
        </script>
{% endblock script %}

chat/templates/chat/rooms.html
{% extends "base.html" %}

{% block title %}  Chat | Public rooms {% endblock title %}

{% block content %}
        <style>
                .user-rooms, .public-rooms {
                        margin: 0 auto;
                        padding: 5px 10px;
                        display: flex;
                        justify-content: center;
                        align-items: center;
                }
                .room-box {
                        background-color: gray;
                        width: 250px;
                        text-align: center;
                        padding: 10px 5px;
                        border-radius: 8px;
                        margin: 5px 10px;
                }
                .room-box small {
                        font-size: 13px;
                        float: left;
                        margin: 20px 10px;
                }
                .room-name {
                        font-size: larger;
                }

                .public-rooms-header-text, .user-rooms-header-text {
                        font-weight: 500;
                        text-align: center;
                        margin: 0 10px;
                }
        </style>

        <div class="rooms">
                {% if user_rooms %}
                        <h2 class="user-rooms-header-text">Personal rooms</h2>
                        <div class="user-rooms">
                        {% for room in user_rooms %}
                                <div class="room-box">
                                        <div><span class="room-name">{{room}}</span></div>
                                        <div><a href="{% url 'chat:join_room' room.slug %}">Join</a></div>
                                        <div><small>Created by you</small></div>
                                </div>
                        {% endfor %}
                        </div>
                {% endif %}
                

                <h2 class="public-rooms-header-text">Public rooms</h2>
                <div class="public-rooms">
                        
                {% for room in all_rooms %}
                <div class="room-box">
                        <div><span class="room-name">{{room}}</span></div>
                        <div><a href="{% url 'chat:join_room' room.slug %}">Join</a></div>
                        <div><small>Created by {{room.owner}}</small></div>
                </div>
                {% endfor %}
                </div>

        </div>

{% endblock content %}