account/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path("profile/<user_id>/", account_view , name="profile"),
    path("profile/<user_id>/edit/", edit , name="edit"),
    path("profile/<user_id>/friends/", list_friends , name="list-friends"),
    path("profile/<user_id>/frequest/", list_friend_requests , name="list-friend-requests"),
    path("profile/<id>/add/", send_friend_request , name="add-friend"),
    path("profile/<id>/accept/", accept_friend_request , name="accept-friend"),
    path("profile/<user_id>/remove/", remove_friend , name="remove-friend"),
    path('register/', register, name="register"),
    path('login/', LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='account/logout.html'), name='logout'),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
]

chat/urls.py
from django.urls import path
from .views import *

app_name = 'chat'

urlpatterns = [
    path('', home, name="home"),
    path('search', search, name="search"),
    path('rooms', list_public_chat_rooms, name="list_rooms"),
    path('room/<slug:slug>', join_room, name="join_room"),
]

djangochat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls', namespace='chat')),
    path('account/', include('account.urls', namespace='account'),
    )
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/footer.html
<footer>
        <h1>
                END
        </h1>
</footer>

templates/snippets/header.html
{% load static %}
<header>
        <div class="logo">
                <a href="{% url 'chat:home' %}"><img src="{% static 'chat/img/django.svg' %}" alt="LOGO" width="50" height="50"></a>
                <span><a href="{% url 'chat:home' %}">Chat</a></span>
                {% if user.is_authenticated %}
                <form action="{% url 'chat:search' %}" method="get">
                        <input type="search" name="friend" id="friend" placeholder="Search for a friend ...">
                </form>
                {% endif %}  
        </div>
        <div class="bars">
                <i class="fa-solid fa-bars" style="color: white;"></i>
        </div>
        <nav class="nav">
                <ul class="nav_links">
                        {% if request.user.is_authenticated %}
                        
                                <li><a href="#"><i class="fa-solid fa-bell"></i></a></li>
                                <li><a href="{% url 'chat:list_rooms' %}"><i class="fa-solid fa-message"></i></a></li>
                                <li><a href="{% url 'account:profile' request.user.id %}"><i class="fa-solid fa-user"></i></a></li>
                                <li><a onmouseover="this.style.backgroundColor='#ff0000'" onmouseout="this.style.backgroundColor=''" href="{% url 'account:logout' %}"> Logout </a></li>

                                
                        {% else %}
                                <li><a href="{% url 'account:login' %}"><span>Login</span></a></li>
                                <li><a href="{% url 'account:register' %}"><span>Sign In</span></a></li>
                        {% endif %}
                </ul>
        </nav>
</header>